"""Swedish architecture copy; component IDs, geometry and flow topology stay shared."""

NODES = {
    "browser": ("Din webbläsare", "Chatt, kartor och nedladdning",
        "Du ställer frågor i Eneo och öppnar kartorna och exportfilerna som assistenten lämnar tillbaka. Även andra MCP-klienter kan använda geodatatjänsten.",
        [("Åtkomst", "Webbplatserna nås via installationens HTTPS-ingång och konfigurerade nätverksåtkomst."),
         ("Kartvisning", "MapLibre eller Origo ritar kartan i webbläsaren. MapLibre kan hämta bakgrundskartor direkt från CARTO."),
         ("Identitet", "Ett användarkonto i Eneo och en identitet knuten till en geodata-API-nyckel är separata identiteter.")]),
    "gateway": ("HTTPS-ingång", "Omvänd proxy · åtkomst",
        "En omvänd proxy tar emot HTTPS och styr anrop till Eneo och Geodata. Värdnamn och nätverksbegränsningar väljs för installationen. Nätverksåtkomst ersätter inte inloggning i tjänsterna.",
        [("Eneo", "Den konfigurerade Eneo-adressen leder till webbgränssnittet och backend-API:et."),
         ("Geodata", "Den konfigurerade Geodata-adressen leder till Caddy; /exports/ leder till MinIO."),
         ("Nätverk och TLS", "Certifikat och förnyelse konfigureras för installationen. Ett privat nätverk eller VPN, exempelvis Tailscale, kan begränsa åtkomsten oberoende av serverhårdvaran.")]),
    "caddy": ("Geodatarouter", "Caddy · intern HTTP",
        "En liten omvänd proxy styr geodatatrafiken till rätt container och strömmar MCP-svar utan buffring.",
        [("/mcp", "Strömmande HTTP till MCP-servern på port 8000."),
         ("/oauth/…", "Även anrop för auktorisering och upptäckt går till MCP."),
         ("Övriga sökvägar", "Översikt, arkitektur, kartor och data går till kartvisartjänsten på port 8001.")]),
    "viewer": ("Kartor och översikt", "FastAPI · MapLibre / Origo",
        "Kartvisartjänsten läser sparade kartbeskrivningar och levererar kartor, lagerdata, arbetsyteöversikter och den här sidan. Ingen språkmodell behövs för att rita kartan.",
        [("Kartdata", "PostGIS → GeoJSON eller vektorplattor. Mindre MapLibre-lager använder GeoJSON; stora lager använder MVT."),
         ("Två kartvisare", "MapLibre använder Web Mercator. Origo använder EPSG:3014 med kompatibla rasterbakgrunder."),
         ("Åtkomst", "Översiktssidor kräver en signerad inloggningscookie. Kart- och datalänkar använder ett svårgissat kart-ID och kontrollerar att lagret ingår i kartan."),
         ("Flygbilder", "Registrerad WMS hämtas genom en proxy på servern. Kartor med förändringsanalys får reglage för före- och efterbilder.")]),
    "basemap": ("CARTO-bakgrund", "Kartplattor till webbläsaren",
        "CARTO tillhandahåller gatukartan Positron som MapLibre använder som bakgrund. Den är separat från ortofotona som används för förändringsanalys.",
        [("Nätverk", "Webbläsaren hämtar bakgrundskartans plattor från CARTO."),
         ("Koordinater", "Plattor i Web Mercator passar MapLibre. Origo behöver en bakgrund som är kompatibel med EPSG:3014.")]),
    "eneo": ("Eneo", "Chatt och verktygsanrop",
        "Eneo håller reda på samtalet, anropar den valda språkmodellen, utför dess verktygsanrop och för tillbaka resultaten till samtalet. Geodata-assistenten har både geodata-MCP och internetsökning anslutna.",
        [("Drift", "Webbgränssnitt, backend och bakgrundsprocess körs i separata containrar."),
         ("Modellanrop", "Eneo skickar samtal och verktygsresultat till chattmodellen via sin konfigurerade modellanslutning."),
         ("Verktygsanslutning", "Eneo autentiserar sig mot geodata-MCP med sin konfigurerade servernyckel."),
         ("Resultat", "Svaret länkar till riktiga kartor och exportfiler som verktygen har skapat.")]),
    "mcp": ("Geodata MCP", "8 verktyg · vald arbetsyta",
        "MCP-servern omvandlar verktygsanrop till katalogsökningar, SQL, arbetsyteåtgärder eller köade jobb. Den kontrollerar argument och behörighet och lämnar strukturerade resultat till assistenten.",
        [("Identitet", "En bearer-API-nyckel eller OAuth-token identifierar en geodataanvändare."),
         ("SQL", "query använder en skrivskyddad roll och en tidsgräns på 15 sekunder. layer skriver härledda tabeller i den valda arbetsytan som användaren äger."),
         ("Långvariga jobb", "load, analyze och export lägger jobb i app.jobs i PostgreSQL och returnerar ett jobb-ID om arbetet fortfarande pågår."),
         ("Sökning", "Katalog- och dokumentsökning kombinerar trigram och vektorer. Sökfrasens vektor skapas av den lokala jobbtjänsten.")]),
    "ops": ("Tjänstestyrning", "Värdåtkomst för administratör",
        "Administratörens sida Tjänster kommunicerar med en begränsad styrenhet på värddatorn. Arkitektursidan förklarar bara systemet och startar eller stoppar aldrig någon tjänst.",
        [("Anslutning", "En privat Unix-socket och en token på serversidan kopplar kartvisaren till styrenheten."),
         ("Omfattning", "Bara konfigurerade tjänsteåtgärder tillåts. Kartvisaren får ingen åtkomst till Docker-socketen."),
         ("Spårbarhet", "Tjänsteåtgärder sparas i en underhållslogg. Aktuell driftstatus finns på sidan Tjänster.")]),
    "model": ("Modell-API", "Samtal och bildanalys",
        "Två oberoende anropare använder separat konfigurerade modellanslutningar: Eneo för samtal och geodatatjänsten för förändringsanalys, granskning av PDF:er/bilder och OCR. De delar varken samtal eller kontextfönster.",
        [("Modell", "Den konfigurerade modellen bearbetar text och bilder via ett modell-API."),
         ("Samtalsflöde", "Eneo skickar samtalet och utvalda verktygsresultat som kontext."),
         ("Bildflöde", "Jobbtjänsten skickar ett separat par av före- och efterutsnitt per anrop, med detail=high och upp till 16 384 utgående token."),
         ("Nätverksgräns", "Prompter och bifogade bilder skickas till det konfigurerade modell-API:et. Modelltjänsten avgör hur många visuella token som faktiskt används.")]),
    "eneo-state": ("Eneos lagring", "PostgreSQL / pgvector + Redis",
        "Eneo har en egen databas och Redis-instans, separata från geodatabasen. De hanterar Eneos applikationsdata och bakgrundsjobb.",
        [("Databas", "Användare, assistenter, samtal och Eneos inställningar lagras här."),
         ("Redis", "Stöder Eneos bakgrundsbearbetning. Geodataanalysens jobb köas inte här."),
         ("Separation", "Arbetsytornas geometrier, ursprungshistorik och kartbeskrivningar finns i den andra PostgreSQL-instansen.")]),
    "worker": ("Geodata-jobbtjänst", "GDAL · jobb · textvektorer",
        "Jobbtjänsten hämtar ett köat jobb från PostgreSQL, utför arbetet och sparar resultatet. Den läser in dataset, bearbetar dokument, jämför flygbilder och skapar exportfiler.",
        [("Jobbkö", "Den nuvarande jobbtjänsten bearbetar ett köat geodatajobb åt gången. Köade jobb finns kvar om MCP-anslutningen bryts."),
         ("Bildjämförelse som standard", "Bildpar på 800 pixlar, 50 % överlappning och fyra samtidiga modellanrop inom ett jobb. Resultaten är ungefärliga rutor för granskning."),
         ("SAM3 som alternativ", "backend=\"sam3\" skickar varje bildårgång till den lokala segmenteraren och jämför sedan maskerna i PostGIS."),
         ("Dokument", "inspect har två lägen: transcribe returnerar sidornas fullständiga text; answer ställer frågor till bildmodellen om de ursprungliga sidbilderna. Båda ger sidhänvisningar. PDF-inläsning delar extrahering och OCR och håller varje indexerat textavsnitt inom sin källsida."),
         ("Textvektorer", "En konfigurerad lokal textmodell skapar 256-dimensionella vektorer via /embed. Modellvikterna cachas på en beständig volym.")]),
    "database": ("Geodatabas", "PostgreSQL · PostGIS · pgvector",
        "Här finns geodatasystemets beständiga innehåll: sökbara metadata, gemensamma källager, arbetsyteresultat, jobbstatus, kartbeskrivningar och ursprungshistorik.",
        [("Geometri", "Lagrade geodata använder EPSG:3014. Bildutsnitt bearbetas i EPSG:3006 och omvandlas tillbaka när resultaten sparas."),
         ("Scheman", "catalog = metadata; ref = gemensamma data; ws_* = arbetsytetabeller; doc = dokumenttext; app = styrning och loggar."),
         ("Arbetsytor", "Ägarskapet är knutet till geodatanyckeln. En nyckel kan äga flera namngivna arbetsytor, med en aktiv standardarbetsyta."),
         ("Beständighet", "En PostgreSQL-volym bevarar data även när containern återskapas.")]),
    "sources": ("Geodata och flygbilder", "WFS · WMS · STAC · filer",
        "Kommunala och nationella tjänster tillhandahåller källdata. Katalogregistrering beskriver en källa; inläsning kopierar utvalda vektordata eller dokument till det lokala systemet. WMS-bilder kan hämtas vid behov.",
        [("Protokoll", "WFS, WMS/WMTS, OGC API Features, STAC, filer, PDF och text stöds."),
         ("Ortofoton", "Förändringsanalysen läser geografiskt matchade utsnitt från STAC/COG eller WMS-lager för olika årgångar, exempelvis Sundsvalls vidareförmedlade Lantmäteribilder."),
         ("Inloggningsuppgifter", "Uppgifter för skyddade källor stannar i jobb- och kartvisartjänsterna, inte i modellprompter eller källkatalogen.")]),
    "web-search": ("Internetsökning MCP", "Separat lokal verktygsserver",
        "Eneos internetsökning är en separat MCP-anslutning. Den söker på den öppna webben, inte i geodatakatalogen, och styr ingen interaktiv webbläsare.",
        [("Implementation", "En lokal FastMCP-tjänst exponerar web_search via DDGS med konfigurerade söktjänster."),
         ("Resultat", "Sökresultatens text och källänkar går tillbaka till assistenten."),
         ("Nätverksgräns", "Sökfraserna skickas till externa söktjänster.")]),
    "sam3": ("SAM3", "Valbar segmentering",
        "SAM3 segmenterar efterfrågade objekt lokalt. Den kan väljas uttryckligen i stället för bildmodellen för förändringsanalys och behövs inte för ett bildanalysjobb.",
        [("Anslutning för förändringsanalys", "Den konfigurerade segmenteringstjänsten returnerar masker för varje bildårgång. Jobbtjänsten omvandlar maskerna till polygoner och jämför dem."),
         ("Hårdvara", "SAM3 körs som en separat modelltjänst. Hårdvarukraven beror på vald backend; arkitekturen förutsätter ingen viss GPU-modell."),
         ("Skillnad", "SAM3 returnerar segmenteringsmasker. Bildmodellen returnerar ungefärliga rutor med synliga belägg och kvalitativ säkerhetsbedömning.")]),
    "exports": ("Exportfiler", "MinIO · S3-kompatibel lagring",
        "Jobbtjänsten skriver GIS-filer och separata filer med ursprungsinformation till MinIO. Assistenten lämnar nedladdningslänkar; geometrin återskapas inte från chattens text.",
        [("Format", "GeoPackage, GeoJSON, CSV och Parquet. GeoJSON exporteras i EPSG:4326."),
         ("Åtkomst", "Nedladdningar använder signerade länkar som gäller i 24 timmar och nås via den konfigurerade exportadressen med dess nätverkspolicy."),
         ("Förnya länkar", "export(job_id=…) skapar nya signerade länkar till befintliga filer utan att köra om analysen.")]),
    "web": ("Öppna webben", "Sökmotorer och källor",
        "Externa sökmotorer levererar webbresultat till internetsökverktyget. Källorna kompletterar den registrerade geodatakatalogen men ersätter den inte.",
        [("Användning", "Hitta bakgrundsinformation och källhänvisningar."),
         ("Avgränsning", "Webbsökning är ingen webbläsarautomatisering och utför inga åtgärder på webbplatserna den hittar.")]),
}

EDGES = dict(zip([
    "access", "chat", "route", "tools-route", "pages", "tools", "chat-model", "chat-state",
    "internet-tool", "search-web", "tool-data", "embedding", "jobs", "image-model", "source-data",
    "local-model", "export-files", "map-data", "raster", "background", "control",
], [
    "HTTPS via konfigurerad nätverksåtkomst", "Chattgränssnitt och API", "Geodataanrop", "Strömmande HTTP för MCP",
    "Sidor och kartdata", "Autentiserade verktygsanrop", "Samtal och verktygsresultat som kontext",
    "Applikationsdata och bakgrundsjobb", "Separat MCP-anslutning", "Extern webbsökning",
    "SQL, arbetsytor och nya jobb", "Lokala vektorer för sökfraser", "Jobbtjänsten hämtar jobb och skriver tillbaka resultat",
    "Par av ortofotoutsnitt", "Läs in data eller hämta bildutsnitt", "Lokala segmenteringsanrop",
    "GIS-filer och ursprungsinformation", "Läs kartbeskrivningar och geodata", "WMS-proxy på serversidan",
    "MapLibre i webbläsaren hämtar kartplattor", "Privat Unix-socket; endast administratörsåtgärder",
], strict=True))

FLOWS = {
    "query": ("Ställ en geodatafråga", "Från fråga till ett svar grundat i data.", [
        ("Öppna Eneo", "Webbläsaren når chatten via installationens HTTPS-ingång."),
        ("Planera med chattmodellen", "Eneo skickar samtalskontext till chattmodellen. Modellen kan begära verktygsanrop."),
        ("Anropa geodataverktyg", "Eneo utför verktygsanropet med sin geodatanyckel och den valda arbetsytan."),
        ("Hitta och fråga efter data", "Katalogsökningen använder lokala textvektorer när de är tillgängliga. query kör skrivskyddad rumslig SQL; layer skapar härledda tabeller i arbetsytan."),
        ("Förklara resultatet", "Verktygsresultaten går tillbaka till Eneo och modellen, som skriver svaret. En karta kräver verktyget map; enbart text skapar ingen karta."),
    ]),
    "vision": ("Förändringsanalys · Bildmodell", "Standardmetoden för bildjämförelse.", [
        ("Starta en analys", "analyze skapar ett change_detect-jobb för arbetsytan i app.jobs. Om backend utelämnas väljs bildmodellen."),
        ("Hämta det köade jobbet", "Geodatatjänsten hämtar ett jobb från PostgreSQL. Kön är oberoende av Eneos Redis."),
        ("Läs två bildårgångar", "Jobbtjänsten hämtar geografiskt matchade bildutsnitt och skapar före- och efterpar på 800 pixlar med 50 % överlappning."),
        ("Jämför bildpar", "Upp till fyra anrop körs samtidigt inom jobbet. Varje anrop skickar två bilder till bildmodellen, med separat kontext från Eneos chatt."),
        ("Spara granskningsförslag", "Ungefärliga rutor, belägg, kvalitativ säkerhetsbedömning och täckning sparas i arbetsytan. Fel markeras inte som oförändrade områden."),
        ("Granska och exportera", "Använd map och export på resultattabellen. Rutor kan överlappa, och area_m2 mäter rutans yta, inte byggnadens markavtryck."),
    ]),
    "sam3": ("Förändringsanalys · SAM3", "Ett valbart alternativ med lokal segmentering.", [
        ("Välj SAM3", "Ange backend=\"sam3\" när change_detect startas. Metoden blir mask_compare."),
        ("Läs flygbilder", "Jobbtjänsten hämtar jobbet och läser båda bildårgångarna i geografiskt matchade utsnitt på 1008 pixlar."),
        ("Segmentera båda årgångarna", "Varje bildårgång skickas till den konfigurerade SAM3-tjänsten med engelska objektbegrepp."),
        ("Jämför masker", "Jobbtjänsten omvandlar masker till polygoner och beräknar överlappning i PostGIS för att föreslå tillkomna, borttagna och förändrade objekt."),
        ("Granska resultatet", "Samma arbetsyta, täckningslager, kartor och exportflöde hanterar SAM3-resultat. Även segmenteringsförslag behöver granskas visuellt."),
    ]),
    "map": ("Öppna karta eller export", "Sparade data blir ett delbart resultat.", [
        ("Spara en kartbeskrivning", "map sparar lagerreferenser, stilar och utbredning i app.map_views och returnerar en kartlänk."),
        ("Öppna kartvisaren", "Webbläsaren följer länken via HTTPS-ingången och geodataroutern."),
        ("Visa riktiga data", "Kartvisartjänsten läser PostGIS och levererar GeoJSON eller MVT. Webbläsaren ritar objekten med MapLibre eller Origo."),
        ("Lägg till en bakgrund", "MapLibre-klienten i webbläsaren hämtar CARTO-plattor. Registrerad WMS-bilddata hämtas genom en proxy på servern."),
        ("Ladda ned en GIS-fil", "export köar ett jobb som skriver valt format och ursprungsinformation till MinIO. Signerade länkar returneras genom verktygen och använder den konfigurerade sökvägen /exports/."),
    ]),
    "internet": ("Sök på internet", "Ett separat verktyg från katalogsökningen.", [
        ("Begär webbsökning", "Eneo väljer sitt MCP-verktyg för internetsökning, inte geodataverktyget search."),
        ("Sök i externa källor", "Den lokala söktjänsten skickar frågan till sina DDGS-söktjänster."),
        ("Lämna källor till chatten", "Resultattext och länkar går tillbaka till Eneo. Chattmodellen kan använda dem i svaret; ingen interaktiv webbläsare är inblandad."),
    ]),
}

TOOLS = {"workspace": "Välj och hantera egna arbetsytor", "search": "Hitta katalogposter och dokumentavsnitt",
         "load": "Registrera källor och läs in data", "query": "Skrivskyddad rumslig SQL",
         "layer": "Skapa och utforma härledda lager i arbetsytan", "map": "Spara en karta och returnera dess länk",
         "analyze": "Granska PDF:er/bilder eller köa förändringsanalys med bildmodellen/SAM3", "export": "Skapa eller hämta en GIS-export"}
