"""Page copy in (Swedish, English) pairs. HTML below is trusted static content."""

TEXT = {
    "title": ("Arkitektur", "Architecture"),
    "context": ("Arkitektur / Govtech4all-piloten", "Architecture / Govtech4all pilot"),
    "heading": ("Så blir en fråga till en karta.", "How a question becomes a map."),
    "intro": ("Eneo håller i samtalet. Geodata MCP omsätter det i data, analys och kartor. Utforska komponenterna eller följ ett anrop genom arbetsstationen.", "Eneo brings the conversation. Geodata MCP turns it into data, analysis and maps. Explore the components or follow a request through the workstation."),
    "language": ("Språk", "Language"),
    "notes": ("Data, åtkomst och gränser", "Data, access & limits"),
    "trace": ("Följ ett systemflöde", "Trace a system flow"),
    "overview": ("Hela arkitekturen", "Full architecture"),
    "caption": ("Välj en komponent för att läsa mer", "Select a component to explore it"),
    "related": (" och dess anslutningar", " and its connections"),
    "zoom": ("Diagramzoom", "Diagram zoom"),
    "zoom_out": ("Zooma ut", "Zoom out"), "zoom_in": ("Zooma in", "Zoom in"),
    "fit": ("Anpassa", "Fit"),
    "diagram": ("Interaktiv systemarkitektur. Använd Tab för att välja en komponent och zoomreglagen för att förstora.", "Interactive system architecture. Tab to select a component; use zoom controls to enlarge."),
    "device": ("Din enhet", "Your device"), "workstation": ("5090-arbetsstation", "5090 workstation"),
    "tailnet": ("Nås via tailnet", "Reachable over the tailnet"),
    "external": ("Externa tjänster", "External services"), "outbound": ("Utgående anrop", "Outbound requests"),
    "arrows": ("Pilarna visar logiska anrop och dataflöden. Svaren går tillbaka över samma anslutning.", "Arrows show logical requests and data paths. Responses return on the same connection."),
    "service": ("Tjänst", "Service"), "data": ("Beständig lagring", "Persistent state"),
    "model": ("Modell", "Model"), "source": ("Extern källa", "External source"),
    "client": ("Klient", "Client"), "host_service": ("Tjänst på arbetsstationen", "Workstation service"),
    "external_service": ("Extern tjänst", "External service"),
    "clear": ("Rensa markering", "Clear selection"),
    "flow_steps": ("Flödets steg", "Flow steps"), "step": ("Steg", "Step"), "of": ("av", "of"),
    "previous": ("Föregående steg", "Previous step"), "next": ("Nästa steg", "Next step"),
    "component": ("Komponentbeskrivning", "Component details"), "back": ("Tillbaka till diagrammet", "Back to diagram"),
    "guide": ("En guide till systemet", "A guide to the system"),
    "one": ("Ett samtal.", "One conversation."), "several": ("Flera separata system.", "Several distinct systems."),
    "select": ("Klicka på en komponent för att se dess uppgift, lagrade data och anslutningar.", "Click any component to see its responsibilities, stored data and connections."),
    "default": ("Gemma är standard", "Gemma is the default"),
    "default_detail": ("Chatt och förändringsanalys använder den betalda externa modellen genom separata anrop. SAM3 finns kvar som ett lokalt alternativ.", "Chat and change detection both use the paid external model, through separate calls. SAM3 remains a local option."),
    "persist": ("Data finns kvar efter chatten", "Data survives the chat"),
    "persist_detail": ("Arbetsytelager, jobb, kartor och exportfiler sparas beständigt på arbetsstationen.", "Workspace layers, jobs, maps and exports are persisted on the workstation."),
    "reviewed": ("Driftbeskrivningen granskades den 22 september 2026. Diagrammet förklarar uppbyggnaden och visar inte aktuell driftstatus.", "Deployment guide reviewed 22 September 2026. This diagram explains the design; it is not a live health display."),
    "noscript": ("JavaScript behövs för att välja komponenter och följa flöden i diagrammet. Den fullständiga komponentbeskrivningen finns nedan.", "The diagram needs JavaScript for selection and flow tracing. The complete component reference is available below."),
    "stored": ("Vad lagras, och var?", "What is stored, and where?"),
    "context_note": ("Modellens kontextfönster är inte systemets databas.", "The model’s context window is not the system’s database."),
    "store": ("Lagring", "Store"), "contents": ("Innehåll", "Contents"), "lifetime": ("Livslängd och ägarskap", "Lifetime / ownership"),
    "eight_tools": ("Åtta verktyg, en vald arbetsyta", "Eight tools, one workspace context"),
    "reference": ("Fullständig komponentbeskrivning", "Complete component reference"),
    "documented": ("Arkitekturen dokumenteras i geodata-repot", "Architecture documented in the geodata repository"),
    "repository": ("Källkod", "Repository"), "api": ("Kartvisarens API-referens", "Viewer API reference"),
    "code_source": ("Källkod", "Source"), "connections": ("Anslutningar", "Connections"),
}

STORAGE = {
    "sv": [
        ("Geodata PostgreSQL", "<code>catalog</code> metadata; <code>ref</code> gemensamma källager; <code>doc</code> dokumentavsnitt.", "Sparas på databasvolymen. Gemensamma källdata är separata från arbetsytornas resultat."),
        ("Arbetsytescheman", "<code>ws_*</code> härledda lager, förändringsförslag och täckning.", "En geodatanyckel äger namngivna arbetsytor. Ett uttryckligt <code>workspace_id</code> håller samtidiga samtal isär utan att ändra den gemensamma standardarbetsytan."),
        ("Geodatas <code>app</code>-schema", "Jobb, kartbeskrivningar, lagermetadata, API-nyckelposter, SQL-/MCP-loggar och ursprungshistorik.", "Kartor hänvisar till beständiga lager. Ursprungshistoriken beskriver hur resultaten skapades."),
        ("Eneo PostgreSQL + Redis", "Samtals- och applikationsdata samt Eneos bakgrundsbearbetning.", "Separata applikationslager. Inget av dem är geodataanalysens jobbkö."),
        ("MinIO + modellcache", "GIS-exporter och källhänvisningsfiler i MinIO; nedladdade modellvikter för textvektorer i jobbtjänstens cache.", "Beständiga volymer. Exportlänkar gäller i 24 timmar och kan förnyas."),
    ],
    "en": [
        ("Geodata PostgreSQL", "<code>catalog</code> metadata; <code>ref</code> shared source layers; <code>doc</code> document passages.", "Persisted in the database volume; shared source data is distinct from workspace results."),
        ("Workspace schemas", "<code>ws_*</code> derived layers, change candidates and coverage.", "A geodata credential owns named workspaces. Explicit <code>workspace_id</code> isolates concurrent conversations without switching the shared default."),
        ("Geodata <code>app</code> schema", "Jobs, map specs, layer metadata, API-key records, SQL/MCP audit and provenance.", "Maps reference persisted layers. Provenance records how outputs were produced."),
        ("Eneo PostgreSQL + Redis", "Conversation/application state and Eneo background processing.", "Separate application stores; neither is the geodata analysis queue."),
        ("MinIO + model cache", "GIS exports and citation sidecars in MinIO; downloaded embedding weights in the worker cache.", "Persistent volumes. Export links expire after 24 hours and can be refreshed."),
    ],
}

BOUNDARIES = {
    "sv": [
        ("Åtkomst i flera lager", "Tailscale styr nåbarheten. Eneo har egen inloggning. MCP kontrollerar bearer-nycklar eller OAuth, och översikten kontrollerar en signerad cookie. Kartlänkar ger åtkomst: den som kan nå webbplatsen och har länken kan se lagren i kartan.",
         "Den nuvarande Eneo-anslutningen använder en gemensam geodatanyckel. Därför motsvarar en arbetsyta inte automatiskt en Eneo-användare. Namn som <code>default</code> och <code>govtech4all</code> är arbetsytenamn, inte användaridentiteter."),
        ("Lokalt betyder inte frånkopplat", "Tjänsterna och geodatalagringen körs på arbetsstationen. Eneo skickar modellkontext externt; Gemmas förändringsanalys skickar bildpar externt; internetsökningen skickar sökfrågor. Även källor och bakgrundskartor kräver utgående trafik.",
         "SAM3-bearbetning och katalogens textvektorer körs lokalt. Inloggningsuppgifter för källor stannar på serversidan. Den här sidan innehåller inga nycklar eller lösenord."),
        ("Samtidighet på två nivåer", "Flera personer kan chatta och läsa kartor samtidigt. Den enda geodata-jobbtjänsten bearbetar köade jobb ett i taget, medan en Gemma-analys kan köra fyra bildanrop samtidigt.",
         "Fler jobbprocesser kräver först ändrad hantering av jobblås och återställning. Förändringsanalys begränsas till 2 km² per anrop och 128 bildutsnitt; välj mindre områden för detaljerat arbete. Antalet förslag är inte ett verifierat antal byggnader."),
    ],
    "en": [
        ("Access is layered", "Tailscale controls reachability. Eneo has its own login. MCP checks bearer credentials or OAuth, and the dashboard checks a signed cookie. Map links are capabilities: anyone who can reach the site and has the link can view its included layers.",
         "The current Eneo connection uses a shared geodata credential. A workspace is therefore not automatically one-to-one with an Eneo user. Names such as <code>default</code> and <code>govtech4all</code> are workspace labels, not user identities."),
        ("Local does not mean offline", "The services and geodata stores run on the workstation. Eneo sends model context externally; Gemma change detection sends crop pairs externally; internet search sends search queries. Sources and basemaps also require outbound access.",
         "SAM3 inference and catalog embeddings run locally. Upstream credentials stay server-side. This page contains no keys or passwords."),
        ("Concurrency has two levels", "Multiple people can chat and read maps at the same time. The single geodata worker processes queued jobs one at a time, while a Gemma analysis can run four crop requests concurrently.",
         "Adding worker replicas needs a job-lease and recovery change first. Change detection is capped at 2 km² per request and 128 image windows; use smaller areas for detailed work. Candidate counts are not verified building counts."),
    ],
}
