"""Page copy in (Swedish, English) pairs. HTML below is trusted static content."""

TEXT = {
    "title": ("Arkitektur", "Architecture"),
    "context": ("Arkitektur / Eneo och Geodata MCP", "Architecture / Eneo and Geodata MCP"),
    "heading": ("Så blir en fråga till en karta.", "How a question becomes a map."),
    "intro": ("Eneo håller i samtalet. Geodata MCP omsätter det i data, analys och kartor. Utforska komponenterna eller följ ett anrop genom systemet.", "Eneo brings the conversation. Geodata MCP turns it into data, analysis and maps. Explore the components or follow a request through the system."),
    "language": ("Språk", "Language"),
    "notes": ("Data, åtkomst och gränser", "Data, access & limits"),
    "trace": ("Följ ett systemflöde", "Trace a system flow"),
    "overview": ("Hela arkitekturen", "Full architecture"),
    "caption": ("Välj en komponent för att läsa mer", "Select a component to explore it"),
    "related": (" och dess anslutningar", " and its connections"),
    "zoom": ("Diagramzoom", "Diagram zoom"),
    "zoom_out": ("Zooma ut", "Zoom out"), "zoom_in": ("Zooma in", "Zoom in"),
    "fit": ("Anpassa", "Fit"),
    "diagram": ("Interaktiv systemarkitektur. Använd Tab för att välja en komponent och zoomreglagen för att förstora.", "Interactive system architecture. Tab to select a component; use zoom controls to enlarge."),
    "device": ("Din enhet", "Your device"), "deployment": ("Driftmiljö", "Deployment environment"),
    "network": ("Tjänster och lagring", "Services and storage"),
    "external": ("Externa tjänster", "External services"), "outbound": ("Utgående anrop", "Outbound requests"),
    "arrows": ("Pilarna visar logiska anrop och dataflöden. Svaren går tillbaka över samma anslutning.", "Arrows show logical requests and data paths. Responses return on the same connection."),
    "service": ("Tjänst", "Service"), "data": ("Beständig lagring", "Persistent state"),
    "model": ("Modell", "Model"), "source": ("Extern källa", "External source"),
    "client": ("Klient", "Client"), "host_service": ("Tjänst i driftmiljön", "Deployment service"),
    "external_service": ("Extern tjänst", "External service"),
    "clear": ("Rensa markering", "Clear selection"),
    "flow_steps": ("Flödets steg", "Flow steps"), "step": ("Steg", "Step"), "of": ("av", "of"),
    "previous": ("Föregående steg", "Previous step"), "next": ("Nästa steg", "Next step"),
    "component": ("Komponentbeskrivning", "Component details"), "back": ("Tillbaka till diagrammet", "Back to diagram"),
    "guide": ("En guide till systemet", "A guide to the system"),
    "one": ("Ett samtal.", "One conversation."), "several": ("Flera separata system.", "Several distinct systems."),
    "select": ("Klicka på en komponent för att se dess uppgift, lagrade data och anslutningar.", "Click any component to see its responsibilities, stored data and connections."),
    "default": ("Gemma är standard", "Gemma is the default"),
    "default_detail": ("Chatt och förändringsanalys använder Gemma genom separata anrop. SAM3 är ett valbart alternativ för segmentering.", "Chat and change detection use Gemma through separate calls. SAM3 is an optional segmentation alternative."),
    "persist": ("Data finns kvar efter chatten", "Data survives the chat"),
    "persist_detail": ("Arbetsytelager, jobb, kartor och exportfiler sparas i driftmiljöns databas och objektlagring.", "Workspace layers, jobs, maps and exports persist in the deployment’s database and object storage."),
    "reviewed": ("Diagrammet visar logiska tjänster och dataflöden. Servertyp, hårdvara, värdnamn och nätverksåtkomst väljs för respektive installation. Det är ingen visning av aktuell driftstatus.", "The diagram shows logical services and data flows. Server type, hardware, hostnames and network access are chosen for each deployment. It is not a live health display."),
    "noscript": ("JavaScript behövs för att välja komponenter och följa flöden i diagrammet. Den fullständiga komponentbeskrivningen finns nedan.", "The diagram needs JavaScript for selection and flow tracing. The complete component reference is available below."),
    "stored": ("Vad lagras, och var?", "What is stored, and where?"),
    "context_note": ("Modellens kontextfönster är inte systemets databas.", "The model’s context window is not the system’s database."),
    "store": ("Lagring", "Store"), "contents": ("Innehåll", "Contents"), "lifetime": ("Livslängd och ägarskap", "Lifetime / ownership"),
    "eight_tools": ("Åtta verktyg, en vald arbetsyta", "Eight tools, one workspace context"),
    "reference": ("Fullständig komponentbeskrivning", "Complete component reference"),
    "documented": ("Arkitekturen dokumenteras i geodata-repot", "Architecture documented in the geodata repository"),
    "repository": ("Källkod", "Repository"), "api": ("Kartvisarens API-referens", "Viewer API reference"),
    "code_source": ("Källkod", "Source"), "connections": ("Anslutningar", "Connections"),
}

STORAGE = {
    "sv": [
        ("Geodata PostgreSQL", "<code>catalog</code> metadata; <code>ref</code> gemensamma källager; <code>doc</code> dokumentavsnitt.", "Sparas på databasvolymen. Gemensamma källdata är separata från arbetsytornas resultat."),
        ("Arbetsytescheman", "<code>ws_*</code> härledda lager, förändringsförslag och täckning.", "En geodatanyckel äger namngivna arbetsytor. Ett uttryckligt <code>workspace_id</code> håller samtidiga samtal isär utan att ändra den gemensamma standardarbetsytan."),
        ("Geodatas <code>app</code>-schema", "Jobb, kartbeskrivningar, lagermetadata, API-nyckelposter, SQL-/MCP-loggar och ursprungshistorik.", "Kartor hänvisar till beständiga lager. Ursprungshistoriken beskriver hur resultaten skapades."),
        ("Eneo PostgreSQL + Redis", "Samtals- och applikationsdata samt Eneos bakgrundsbearbetning.", "Separata applikationslager. Inget av dem är geodataanalysens jobbkö."),
        ("MinIO + modellcache", "GIS-exporter och källhänvisningsfiler i MinIO; nedladdade modellvikter för textvektorer i jobbtjänstens cache.", "Beständiga volymer. Exportlänkar gäller i 24 timmar och kan förnyas."),
    ],
    "en": [
        ("Geodata PostgreSQL", "<code>catalog</code> metadata; <code>ref</code> shared source layers; <code>doc</code> document passages.", "Persisted in the database volume; shared source data is distinct from workspace results."),
        ("Workspace schemas", "<code>ws_*</code> derived layers, change candidates and coverage.", "A geodata credential owns named workspaces. Explicit <code>workspace_id</code> isolates concurrent conversations without switching the shared default."),
        ("Geodata <code>app</code> schema", "Jobs, map specs, layer metadata, API-key records, SQL/MCP audit and provenance.", "Maps reference persisted layers. Provenance records how outputs were produced."),
        ("Eneo PostgreSQL + Redis", "Conversation/application state and Eneo background processing.", "Separate application stores; neither is the geodata analysis queue."),
        ("MinIO + model cache", "GIS exports and citation sidecars in MinIO; downloaded embedding weights in the worker cache.", "Persistent volumes. Export links expire after 24 hours and can be refreshed."),
    ],
}

BOUNDARIES = {
    "sv": [
        ("Åtkomst i flera lager", "Installationens nätverkspolicy styr nåbarheten, exempelvis via ett privat nätverk eller VPN. Eneo har egen inloggning. MCP kontrollerar bearer-nycklar eller OAuth, och översikten kontrollerar en signerad cookie. Kartlänkar ger åtkomst: den som kan nå webbplatsen och har länken kan se lagren i kartan.",
         "Om Eneo-anslutningen använder en gemensam geodatanyckel motsvarar en arbetsyta inte automatiskt en Eneo-användare. Arbetsytenamn, exempelvis <code>default</code>, är etiketter och inte användaridentiteter."),
        ("Utgående dataflöden", "Tjänster och geodatalagring finns i driftmiljön. Eneo skickar modellkontext till Gemmas API; bildanalys och OCR skickar bilder och text; internetsökningen skickar sökfrågor. Även källor och bakgrundskartor kräver utgående trafik.",
         "SAM3-bearbetning och katalogens textvektorer körs lokalt. Inloggningsuppgifter för källor stannar på serversidan. Den här sidan innehåller inga nycklar eller lösenord."),
        ("Samtidighet på två nivåer", "Flera personer kan chatta och läsa kartor samtidigt. Den enda geodata-jobbtjänsten bearbetar köade jobb ett i taget, medan en Gemma-analys kan köra fyra bildanrop samtidigt.",
         "Fler jobbprocesser kräver först ändrad hantering av jobblås och återställning. Förändringsanalys begränsas till 2 km² per anrop och 128 bildutsnitt; välj mindre områden för detaljerat arbete. Antalet förslag är inte ett verifierat antal byggnader."),
    ],
    "en": [
        ("Access is layered", "The deployment’s network policy controls reachability, for example through a private network or VPN. Eneo has its own login. MCP checks bearer credentials or OAuth, and the dashboard checks a signed cookie. Map links are capabilities: anyone who can reach the site and has the link can view its included layers.",
         "If the Eneo connection uses a shared geodata credential, a workspace is not automatically one-to-one with an Eneo user. Workspace names such as <code>default</code> are labels, not user identities."),
        ("Outbound data flows", "Services and geodata stores live in the deployment environment. Eneo sends model context to the Gemma API; image analysis and OCR send images and text; internet search sends search queries. Sources and basemaps also require outbound access.",
         "SAM3 inference and catalog embeddings run locally. Upstream credentials stay server-side. This page contains no keys or passwords."),
        ("Concurrency has two levels", "Multiple people can chat and read maps at the same time. The single geodata worker processes queued jobs one at a time, while a Gemma analysis can run four crop requests concurrently.",
         "Adding worker replicas needs a job-lease and recovery change first. Change detection is capped at 2 km² per request and 128 image windows; use smaller areas for detailed work. Candidate counts are not verified building counts."),
    ],
}
